# Generated by Django 5.2.9 on 2025-12-17 14:48

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_newspage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newspage",
            name="body",
            field=wagtail.fields.StreamField(
                [("heading", 0), ("paragraph", 1), ("image", 2)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "full title", "icon": "title"},
                    ),
                    1: ("wagtail.blocks.RichTextBlock", (), {"icon": "pilcrow"}),
                    2: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"icon": "image"},
                    ),
                },
                null=True,
            ),
        ),
    ]
