# Generated by Django 5.2.9 on 2026-01-10 11:45

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0003_alter_newspage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newspage",
            name="body",
            field=wagtail.fields.StreamField(
                [("heading", 0), ("paragraph", 1), ("image", 2)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "full title", "icon": "title"},
                    ),
                    1: ("wagtail.blocks.RichTextBlock", (), {"icon": "pilcrow"}),
                    2: ("news.blocks.ResponsiveImageBlock", (), {"icon": "image"}),
                },
                default=[],
            ),
            preserve_default=False,
        ),
    ]
